spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              apicurio:
                registry:
                  url: http://localhost:8082/api
        binder:
          brokers: localhost:9092

  data:
    mongodb:
      host: localhost