version: '3.8'

services:

  zookeeper:
    image: strimzi/kafka:0.20.0-kafka-2.6.0
    hostname: zoo1
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:0.20.0-kafka-2.6.0
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties \
          --override listeners=$${KAFKA_LISTENERS} \
          --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} \
          --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  apicurio:
    image: apicurio/apicurio-registry-mem:1.3.1.Final
    ports:
      - "8081:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092

volumes:
  mongodb_data: