spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.64.5:16550
      group-id: apicurio-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
      properties:
        spring.json.trusted.packages: "io.dietschi.edu.producerconsumer"
        apicurio:
          registry:
            use-specific-avro-reader: true
            url: http://192.168.64.5:30036/api
    producer:
      bootstrap-servers: 192.168.64.5:16550
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
      properties:
        apicurio:
          registry:
            url: http://192.168.64.5:30036/api
            artifact-id: io.apicurio.registry.utils.serde.strategy.TopicIdStrategy

logging:
  level:
    root: INFO