apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
  labels:
    name: example-apicurioregistry
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
      name: http
  selector:
    app: example-apicurioregistry