apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: dev-cluster
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30100
          brokers:
            - broker: 0
              nodePort: 30101
      - name: tls
        port: 9093
        type: nodeport
        tls: true
        configuration:
          bootstrap:
            nodePort: 30200
          brokers:
            - broker: 0
              nodePort: 30201
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
